[build]
  command = "npm run build"
  publish = "build"
  functions = "functions"

[build.environment]
  GENERATE_SOURCEMAP = "false"
  SKIP_PREFLIGHT_CHECK = "true"
  ESLINT_NO_DEV_ERRORS = "true"
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false
